export default {
    products: [
        {
        _id: '1',
        name: 'Godzilla',
        category: 'Toys',
        image: '/images/toy.jpg',
        price: 25,
        brand: 'Tokyo',
        rating: 4.5,
        numReviews: 10,
    },
    {
        _id: '2',
        name: 'Army Men',
        category: 'Toys',
        image: '/images/army.jpg',
        price: 5,
        brand: 'Playco',
        rating: 4,
        numReviews: 15,
    },
    {
        _id: '3',
        name: 'Barrel of Monkies',
        category: 'Toys',
        image: '/images/barrel-of-monkeys.jpg',
        price: 10,
        brand: 'Nabisco',
        rating: 3,
        numReviews: 5,
    },
    {
        _id: '4',
        name: 'Furby',
        category: 'Toys',
        image: '/images/furby.jpg',
        price: 25,
        brand: 'Tokyo',
        rating: 5,
        numReviews: 10,
    },
    {
        _id: '5',
        name: 'Rubik',
        category: 'Toys',
        image: 'images/rubik.jpg',
        price: 10,
        brand: 'Playco',
        rating: 4.5,
        numReviews: 10,
    },
]
}