export default {
    products: [
        {
        _id: '1',
        name: 'Godzilla',
        category: 'Toys',
        image: '/image/toy.jpg',
        price: 25,
        brand: 'Tokyo',
        rating: 4.5,
        numReviews: 10,
    },
    {
        _id: '2',
        name: 'Army Men',
        category: 'Toys',
        image: '/image/army.jpg',
        price: 5,
        brand: 'Playco',
        rating: 4,
        numReviews: 15,
    },
    {
        _id: '3',
        name: 'Barrel of Monkies',
        category: 'Toys',
        image: '/image/barrel-of-monkies.jpg',
        price: 10,
        brand: 'Nabisco',
        rating: 3,
        numReviews: 5,
    },
    {
        _id: '4',
        name: 'Furby',
        category: 'Toys',
        image: '/image/furby.jpg',
        price: 25,
        brand: 'Tokyo',
        rating: 5,
        numReviews: 10,
    },
    {
        _id: '5',
        name: 'Rubik',
        category: 'Toys',
        image: '/image/rubik.jpg',
        price: 10,
        brand: 'Playco',
        rating: 4.5,
        numReviews: 10,
    },
]
}